name: Run ContinuumWorld Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Julia Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'

      - name: Cache Julia packages
        uses: actions/cache@v3
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia-artifacts-${{ hashFiles('**/Project.toml') }}
          restore-keys: ${{ runner.os }}-julia-artifacts-

      - name: Install dependencies quickly
        run: |
          julia --project -e '
            using Pkg
            Pkg.develop(path=".")
            Pkg.instantiate()
            Pkg.resolve()
          '

      - name: Run tests (fast mode, no plotting)
        run: |
          julia --project -e '
            ENV["CI_NO_PLOTS"] = "true"
            using Pkg
            Pkg.test()
          '
